// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/utube/AccountHub.tsx": () => import("../components/mockups/utube/AccountHub.tsx"),
  "./components/mockups/utube/DownloadManager.tsx": () => import("../components/mockups/utube/DownloadManager.tsx"),
  "./components/mockups/utube/HomeFeedSignedIn.tsx": () => import("../components/mockups/utube/HomeFeedSignedIn.tsx"),
  "./components/mockups/utube/HomeFeedSignedOut.tsx": () => import("../components/mockups/utube/HomeFeedSignedOut.tsx"),
  "./components/mockups/utube/Library.tsx": () => import("../components/mockups/utube/Library.tsx"),
  "./components/mockups/utube/SearchExplore.tsx": () => import("../components/mockups/utube/SearchExplore.tsx"),
  "./components/mockups/utube/Settings.tsx": () => import("../components/mockups/utube/Settings.tsx"),
  "./components/mockups/utube/SignIn.tsx": () => import("../components/mockups/utube/SignIn.tsx"),
  "./components/mockups/utube/VideoPlayer.tsx": () => import("../components/mockups/utube/VideoPlayer.tsx")
};
